using System.Text;

namespace CommandLine.Generators.Emit;

/// <summary>
/// Provides API on top of the string builder for generating formatted C# code.
/// </summary>
internal class CodeWriter
{
    private const string IndentString = "    ";

    private const string FileHeader = $$"""
        // <auto-generated/>
        #nullable enable

        using System.CommandLine;
        """;

    private readonly StringBuilder _buffer;

    private int _indent;

    internal CodeWriter(int bufferCapacity) => _buffer = new StringBuilder(bufferCapacity);

    internal CodeWriter(StringBuilder buffer) => _buffer = buffer;

    /// <summary>
    /// Convert this object into a string representation.
    /// </summary>
    public override string ToString() => _buffer.ToString();

    internal CodeWriter Indent()
    {
        _indent++;

        return this;
    }

    internal CodeWriter Unindent()
    {
        _indent--;

        return this;
    }

    internal CodeWriter AppendFileHeader(
        string fileNamespace = Constants.GeneratedNamespace,
        IEnumerable<string>? usings = null)
    {
        _buffer.AppendLine(FileHeader);

        if (usings is not null)
        {
            foreach (string u in usings)
                _buffer.AppendLine($"using {u};");
        }

        _buffer.AppendLine();
        _buffer.AppendLine($"namespace {fileNamespace};");
        _buffer.AppendLine();

        return this;
    }

    internal CodeWriter StartBlock(string block)
    {
        AppendIndentation();
        _buffer.AppendLine(block);
        AppendIndentation();
        _buffer.AppendLine("{");
        _indent++;

        return this;
    }

    internal CodeWriter EndBlock(string ending = "}", int numBlocks = 1)
    {
        for (int i = 0; i < numBlocks; i++)
        {
            _indent--;
            AppendIndentation();
            _buffer.AppendLine(ending);
        }

        return this;
    }

    internal CodeWriter AppendLine()
    {
        _buffer.AppendLine();

        return this;
    }

    internal CodeWriter AppendLine(string line, bool indented = true)
    {
        if (indented)
            AppendIndentation();

        _buffer.AppendLine(line);

        return this;
    }

    internal CodeWriter AppendLine(IEnumerable<string> lines, bool indented = true)
    {
        if (indented)
            AppendIndentation();

        foreach (string line in lines)
            _buffer.Append(line);

        _buffer.AppendLine();

        return this;
    }

    private void AppendIndentation()
    {
        if (_indent is 0)
            return;

        for (int i = 0; i < _indent; i++)
            _buffer.Append(IndentString);
    }
}
