using System.Text;
using System.Xml.Schema;
using CommandLine.Generators.Models;

namespace CommandLine.Generators.Emit;

/// <summary>
/// Emits the partial class source for a command handler.
/// </summary>
internal static class HandlerEmitter
{
    /// <summary>
    /// Builds the source text for the generated partial class.
    /// </summary>
    /// <param name="model">The command handler model.</param>
    /// <returns>The generated C# source.</returns>
    public static string Emit(CommandHandlerModel model)
    {
        StringBuilder sb = new(8192);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.CommandLine;");
        sb.AppendLine("using System.CommandLine.Parsing;");
        if (model.HasAsyncExecute)
        {
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
        }

        sb.AppendLine();
        sb.Append("namespace ").Append(model.NamespaceName).AppendLine(";");
        sb.AppendLine();
        sb.Append("partial class ").AppendLine(model.ClassName);
        sb.AppendLine("{");
        sb.AppendLine("    static partial void " + Constants.OnCommandDefinedMethodName + "(Command cmd);");
        sb.AppendLine();
        sb.Append("    static partial void ").Append(Constants.OnCommandCreatedMethodName);
        sb.Append('(').Append(model.ClassName).AppendLine(" handler, ParseResult pr);");
        sb.AppendLine();

        EmitGetCommandDefinition(sb, model);
        sb.AppendLine();
        EmitFromParseResult(sb, model);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitGetCommandDefinition(StringBuilder sb, CommandHandlerModel model)
    {
        sb.Append("    public static Command ");
        sb.Append(Constants.GetCommandDefinitionMethodName).AppendLine("()");
        sb.AppendLine("    {");

        foreach (CommandParameterModel parameter in model.Parameters)
            EmitOption(sb, parameter);

        if (model.Parameters.Length > 0)
            sb.AppendLine();

        sb.Append("        Command retVal = new(").Append(Stringify(model.Name)).Append(", ");
        sb.Append(Stringify(model.Description)).AppendLine(");");

        foreach (CommandParameterModel parameter in model.Parameters)
            sb.Append("        retVal.Add(").Append(parameter.ParameterName).AppendLine(");");

        EmitSetAction(sb, model);

        sb.AppendLine();
        sb.Append("        ").Append(Constants.OnCommandDefinedMethodName).AppendLine("(retVal);");
        sb.AppendLine();
        sb.AppendLine("        return retVal;");
        sb.AppendLine("    }");
    }

    private static void EmitOption(StringBuilder sb, CommandParameterModel parameter)
    {
        string optionLong = "--" + NameUtilities.ToKebabCase(parameter.ParameterName);
        bool required = !parameter.IsNullable && !parameter.HasDefaultValue;

        sb.Append("        Option<").Append(parameter.ParameterTypeName).Append("> ");
        sb.Append(parameter.ParameterName).Append(" = new(\"").Append(optionLong).AppendLine("\")");
        sb.AppendLine("        {");
        sb.Append("            Description = ");
        sb.Append(Stringify(parameter.Description)).AppendLine(",");
        if (!string.IsNullOrEmpty(parameter.ValueHint))
        {
            sb.Append("            HelpName = ");
            sb.Append(Stringify(parameter.ValueHint!)).AppendLine(",");
        }

        sb.Append("            Required = ").Append(required ? "true" : "false").AppendLine(",");
        if (parameter.HasDefaultValue && parameter.DefaultValueLiteral is not null)
        {
            sb.Append("            DefaultValueFactory = static _ => ");
            sb.Append(parameter.DefaultValueLiteral).AppendLine(",");
        }

        sb.AppendLine("        };");

        if (parameter.Alias.HasValue)
        {
            sb.Append("        ").Append(parameter.ParameterName).Append(".Aliases.Add(\"-");
            sb.Append(parameter.Alias.Value).AppendLine("\");");
        }
    }

    private static void EmitSetAction(StringBuilder sb, CommandHandlerModel model)
    {
        if (!model.HasExecuteMethod)
            return;

        sb.AppendLine();
        if (model.HasAsyncExecute)
        {
            sb.Append("        retVal.SetAction(static (parseResult, ct) => ");
            sb.Append(Constants.FromParseResultMethodName);
            sb.Append("(parseResult).").Append(Constants.ExecuteAsyncMethodName).AppendLine("(ct));");
        }
        else
        {
            sb.Append("        retVal.SetAction(parseResult => ");
            sb.Append(Constants.FromParseResultMethodName);
            sb.Append("(parseResult).").Append(Constants.ExecuteMethodName).AppendLine("());");
        }
    }

    private static void EmitFromParseResult(StringBuilder sb, CommandHandlerModel model)
    {
        sb.Append("    public static ").Append(model.ClassName).Append(' ');
        sb.Append(Constants.FromParseResultMethodName).AppendLine("(ParseResult pr)");
        sb.AppendLine("    {");
        sb.Append("        ").Append(model.ClassName).Append(" retVal = new(");

        if (model.Parameters.Length is 0)
        {
            sb.AppendLine(");");
        }
        else
        {
            sb.AppendLine();
            for (int i = 0; i < model.Parameters.Length; i++)
            {
                CommandParameterModel parameter = model.Parameters[i];
                string optionLong = "--" + NameUtilities.ToKebabCase(parameter.ParameterName);
                string suppress = parameter.IsNullable ? "" : "!";
                sb.Append("            pr.GetValue<").Append(parameter.ParameterTypeName);
                sb.Append(">(\"").Append(optionLong).Append("\")").Append(suppress);
                if (i < model.Parameters.Length - 1)
                    sb.Append(',');

                sb.AppendLine();
            }

            sb.AppendLine("        );");
        }

        sb.AppendLine();
        sb.Append("        ").Append(Constants.OnCommandCreatedMethodName).AppendLine("(retVal, pr);");
        sb.AppendLine();
        sb.AppendLine("        return retVal;");
        sb.AppendLine("    }");
    }

    private static string Stringify(string value)
    {
        StringBuilder sb = new(value.Length);
        sb.Append("@\"");
        sb.Append(value.Replace("\"", "\"\""));
        sb.Append('"');

        return sb.ToString();
    }
}
