using System.Collections.Immutable;
using System.Text;
using CommandLine.Generators.Models;

namespace CommandLine.Generators.Emit;

/// <summary>
/// Emits the root command extensions aggregator class.
/// </summary>
internal static class RootExtensionsEmitter
{
    /// <summary>
    /// Builds the source text for the aggregator class.
    /// </summary>
    /// <param name="models">Collected command handler models.</param>
    /// <returns>The generated C# source.</returns>
    public static string Emit(ImmutableArray<CommandHandlerModel> models)
    {
        StringBuilder sb = new(4096);
        sb.AppendLine($$"""
            // <auto-generated/>
            #nullable enable

            using System.CommandLine;

            namespace {{Constants.GeneratedNamespace}};

            internal static class RootCommandExtensions
            {
                internal static void AddCommandsFromAssembly(this RootCommand root)
                {
            """);

        foreach (CommandHandlerModel model in models)
        {
            if (string.IsNullOrEmpty(model.ClassName) || string.IsNullOrEmpty(model.NamespaceName))
                continue;

            sb.AppendLine(
$"""
        root.Add(global::{model.NamespaceName}.{model.ClassName}.{Constants.GetCommandDefinitionMethodName}());
""");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
