name: CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Cache NuGet packages
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore .

      - name: Build analyzer
        run: dotnet build --no-restore --configuration Debug

      - name: Run tests
        run: dotnet test --no-build --configuration Debug --verbosity normal
